# agent_perimeter/report/html.py
"""Server-rendered report — screen 6.

Deliberately not part of the Next.js application: the Week 4 census report is
generated by this same module, so if the UI slips the report still ships.

Print is a first-class target. These get printed and emailed to auditors, so
severity carries a glyph and a text label rather than colour alone, and the
methodology footer travels with the document.
"""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from agent_perimeter.checks.registry import Skipped
from agent_perimeter.eval.score import CheckScore
from agent_perimeter.model.edge import CapabilityEdge
from agent_perimeter.model.feature import BUNDLES
from agent_perimeter.model.finding import Finding
from agent_perimeter.transport.revision import Fingerprint

TEMPLATES = Path(__file__).parent / "templates"

SEVERITY_GLYPHS = {
    "critical": "!!",
    "high": "!",
    "medium": "=",
    "low": "-",
    "info": "i",
}

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}


def render_report(
    *,
    findings: list[Finding],
    edges: list[CapabilityEdge],
    fingerprint: Fingerprint,
    target: str,
    skipped: list[Skipped],
    scores: list[CheckScore],
) -> str:
    env = Environment(
        loader=FileSystemLoader(TEMPLATES), autoescape=select_autoescape(["html", "j2"])
    )
    template = env.get_template("report.html.j2")

    claimed = fingerprint.revision_claimed
    bundle = BUNDLES.get(claimed, frozenset()) if claimed else frozenset()
    gaps = len(bundle - fingerprint.features)

    return template.render(
        css=(TEMPLATES / "report.css").read_text(encoding="utf-8"),
        target=target,
        findings=sorted(findings, key=lambda f: SEVERITY_ORDER[f.severity.value]),
        edges=edges,
        skipped=skipped,
        scores=scores,
        glyphs=SEVERITY_GLYPHS,
        revision_claimed=claimed.value if claimed else "unknown",
        features=sorted(f.value for f in fingerprint.features),
        bundle_size=len(bundle) or len(fingerprint.features),
        conformance_gaps=gaps,
    )
