"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-30 15:06:17.880524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_ref', sa.Text(), nullable=False),
    sa.Column('scope_file_id', sa.String(length=36), nullable=True),
    sa.Column('revision_claimed', sa.String(length=16), nullable=True),
    sa.Column('revision_observed', sa.String(length=16), nullable=True),
    sa.Column('feature_set_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('tool_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('check_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('calibration_id', sa.String(length=36), nullable=True),
    sa.Column('cwe', sa.String(length=16), nullable=False),
    sa.Column('taxonomy_refs_json', sa.JSON(), nullable=False),
    sa.Column('feature_requirements_json', sa.JSON(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reproduction', sa.Text(), nullable=False),
    sa.Column('claim_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_finding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.CheckConstraint('validated = false', name='ck_secret_finding_never_validated'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('auth_mode', sa.String(length=32), nullable=True),
    sa.Column('tls_detail', sa.JSON(), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('extensions_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description_hash', sa.String(length=64), nullable=False),
    sa.Column('input_schema_json', sa.JSON(), nullable=False),
    sa.Column('annotations_json', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_edge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('derived_from', sa.String(length=16), nullable=False),
    sa.Column('claim_json', sa.JSON(), nullable=False),
    sa.CheckConstraint("derived_from IN ('schema', 'description', 'probe', 'artifact')", name='ck_capability_edge_derived_from'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('old_hash', sa.String(length=64), nullable=False),
    sa.Column('new_hash', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('blob_ref', sa.Text(), nullable=False),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('drift_event')
    op.drop_table('capability_edge')
    op.drop_table('tool')
    op.drop_table('server_profile')
    op.drop_table('secret_finding')
    op.drop_table('finding')
    op.drop_table('scan')
    # ### end Alembic commands ###
