"""add secret_finding.expires_at

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-30 20:06:43.325873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nullable: this is the project's first ADD COLUMN migration against a
    # table that can already hold rows (Task 4's columns all came from
    # create_table, always empty at creation). NOT NULL with no default here
    # would fail against any populated secret_finding table in a real
    # deployment. New rows still get a value via the ORM-side default
    # (models.py); purge_expired_secrets() treats a NULL as also expired.
    op.add_column('secret_finding', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secret_finding', 'expires_at')
    # ### end Alembic commands ###
