"""census tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-31 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('census_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('population_size', sa.Integer(), nullable=False),
    sa.Column('fetch_failures', sa.Integer(), nullable=False),
    sa.Column('tool_version', sa.String(), nullable=False),
    sa.Column('method_hash', sa.String(), nullable=False),
    sa.Column('tier2_n', sa.Integer(), nullable=True),
    sa.Column('registry_endpoint', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('census_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('census_run_id', sa.Integer(), nullable=False),
    sa.Column('registry_id', sa.String(), nullable=False),
    sa.Column('coords_digest', sa.String(), nullable=False),
    sa.Column('ecosystem', sa.String(), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.Column('distribution', sa.String(), nullable=False),
    sa.Column('sdk_version', sa.String(), nullable=True),
    sa.Column('feature_set_json', sa.JSON(), nullable=False),
    sa.Column('fetch_status', sa.String(), nullable=False),
    sa.Column('fetch_detail', sa.String(), nullable=True),
    sa.Column('rank_metric', sa.Integer(), nullable=True),
    sa.Column('rank_metric_source', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['census_run_id'], ['census_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_census_record_coords_digest'), 'census_record', ['coords_digest'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_census_record_coords_digest'), table_name='census_record')
    op.drop_table('census_record')
    op.drop_table('census_run')
    # ### end Alembic commands ###
